version: "0.0.0"

services:

  talkydoki_redis:
    image: redis
    container_name: talkydoki_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - talkydoki_db_net

  talkydoki_rabbitmq:
    container_name: talkydoki_rabbitmq
    build:
      context: .
      dockerfile: rabbitmq.Dockerfile
    image: talkydoki_rabbitmq_img
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    command: [ "rabbitmq-server" ]
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: unless-stopped
    networks:
      - talkydoki_db_net

networks:
  talkydoki_db_net:
